ACRONYMS = {
    'GCD': ['GCD'], 
    'PNGS': ['PNGS'], 
    'OS': ['OS'], 
    'URL': ['URL'],
    'OBJC': ['OBJC'], 
    'ARC': ['ARC'], 
    'CXX': ['CXX'], 
    'NSENUM': ['NS', 'Enum'], 
    'LSV': ['LSV'], 
    'SEQ': ['SEQ'], 
    'CST': ['CST'], 
    'DTOR': ['DTOR'], 
    'ISA': ['ISA'], 
    'NONNULL': ['NONNULL'], 
    'IVARS': ['IVARS'], 
    'XNU': ['XNU'], 
    'NONARC': ['NONARC'], 
    'HIDPI': ['HIDPI'], 
    'SDK': ['SDK'], 
    'TIFF': ['TIFF'], 
    'CPP': ['CPP'], 
    'VFS': ['VFS'], 
    'SYMLINKS': ['SYMLINKS'], 
    'CodeSignEntitlements': ['CodeSign', 'Entitlements'], 
    'CodeSignResourceRules': ['Code', 'SignResourceRules'],
    'DEXT': ['DEXT'], 
    'KEXT': ['KEXT'], 
    'SSE': ['SSE'], 
    'SPI': ['SPI'], 
    'DSYMUTIL': ['DSYM', 'Util'], 
    'DTRACE': ['DTRACE'], 
    'DAWRF': ['DAWRF'], 
    'DSYM': ['DSYM'], 
    'DYLIB': ['DYLIB'], 
    'NS': ['NS'], 
    'MSGSEND': ['MSGSEND'], 
    'INSTALLSRC': ['Install', 'SRC'], 
    'SUBDIRECTORY': ['Sub', 'Directory'],
    'ExpandBuildSettings': ['Expand', 'BuildSettings'], 
    'GCC3': ['GCC3'], 
    'GCC': ['GCC'], 
    'CW': ['CW'], 
    'ASM': ['ASM'], 
    'RTTI': ['RTTI'], 
    'SSE3': ['SSE3'], 
    'SSE41': ['SSE41'], 
    'SSE42': ['SSE42'], 
    'ARCS': ['ARCS'], 
    'MACOSX': ['Mac', 'OSX'], 
    'ABI': ['ABI'], 
    'PFE': ['PFE'], 
    'OFFSETOF': ['Offset', 'Of'],
    'CFLAGS': ['CFLAGS'], 
    'GeneratedPkgInfoFile': ['Generated', 'PKGInfoFile'], 
    'IBC': ['IBC'], 
    'MACOS': ['MAC', 'OS'], 
    'NIBS': ['NIBS'], 
    'IOS': ['IOS'], 
    'IBSC': ['IBSC'], 
    'IIG': ['IIG'], 
    'InfoPlistPath': ['Info', 'PlistPath'], 
    'CFLAGS': ['CFLAGS'], 
    'CPLUSPLUSFLAGS': ['C', 'Plus', 'Plus', 'Flags'],
    'LD': ['LD'], 
    'LTO': ['LTO'], 
    'LEXFLAGS': ['LEX', 'Flags'], 
    'LIBTOOL': ['LIB', 'Tool'], 
    'LLVM': ['LLVM'], 
    'LTO': ['LTO'], 
    'LM': ['LM'], 
    'SWIFTUI': ['Swift', 'UI'], 
    'LOCROOT': ['LOC', 'Root'], 
    'LOCSYMROOT': ['LOC', 'SYM', 'Root'], 
    'MAPC': ['MAPC'], 
    'MIG': ['MIG'], 
    'MOMC': ['MOMC'], 
    'MTLCOMPILER': ['MTL', 'Compiler'], 
    'MTLINKER': ['MT', 'Linker'], 
    'MTL': ['MTL'], 
    'NASM': ['NASM'], 
    'OPENCL': ['OPENCL'], 
    'MAD': ['MAD'], 
    'BC': ['BC'], 
    'CFLAGS': ['CFLAGS'], 
    'DOCC': ['DocC'], 
    'IIG': ['IIG'],
    'LDRFLAGS': ['LDR', 'Flags'], 
    'LIBTOOLFLAGS': ['LIB', 'Tool', 'Flags'], 
    'MIGFLAGS': ['MIG', 'Flags'], 
    'OSACOMPILEFLAGS': ['OSA', 'Compile', 'Flags'], 
    'OSAFLAGS': ['OSA', 'Flags'], 
    'RCPROJECT': ['RC', 'Project'], 
    'RESMERGERFLAGS': ['RES', 'Merger', 'Flags'], 
    'REZFLAGS': ['REZ', 'Flags'], 
    'STDLIB': ['STD', 'Lib'],
    'TAPI': ['TAPI'], 
    'USDZ': ['USDZ'], 
    'PBDEVELOPMENTPLIST': ['PB', 'Development', 'Plist'], 
    'PBXCP': ['PBXCP'], 
    'CVS': ['CVS'], 
    'HG': ['HG'], 
    'SVN': ['SVN'], 
    'RemoveFile': ['Remove', 'File'], 
    'SDKDB': ['SDKDB'], 
    'SECTORDER': ['SECT', 'Order'], 
    'SRCROOT': ['SRC', 'Root'], 
    'LOC': ['LOC'], 
    'WMO': ['WMO'],
    'SigningCert': ['Signing', 'Cert'], 
    'API': ['API'], 
    'USDZ': ['USDZ'], 
    'PFE': ['PFE'], 
    'XIB': ['XIB'], 
    'XPCSERVICES': ['XPC', 'Services'], 
    'YACC': ['YACC'], 
    'YACCFLAGS': ['YACC', 'Flags'],
    'ASSETCATALOG': ['Asset', 'Catalog'],
    'OPENCL': ['Open', 'CL']
}